// Hero copy and the sample call it plays. The sample is SYNTHETIC (generated by
// apps/www/scripts/make-sample-call.ts): `at` is each line's start in seconds in
// public/sample-call.m4a, so the transcript can follow the audio. Replace the file,
// the cue times and the lines together when a real recording exists.

export const hero = {
  eyebrow: "Voice AI for Indian real estate",
  title: "Turn property enquiries into qualified site visits.",
  sub: "Revenue OS calls new leads in Hinglish, qualifies budget and timeline, and follows up on WhatsApp\u2060—so your sales team can focus on buyers ready to visit.",
  secondary: "Hear a sample call",
} as const;

type Speaker = "agent" | "buyer";

export interface CallLine {
  at: number;
  who: Speaker;
  text: string;
}

export const sampleCall = {
  src: "/sample-call.m4a",
  seconds: 42,
  label: "Sample call",
  disclosure:
    "Recreated with basic text-to-speech, not the voice used on real calls. Names and figures are illustrative.",
  lead: "Rohan Mehta",
  source: "Imported enquiry · 2 BHK · Whitefield, Bengaluru",
  calledAfter: "Called 2 min after import",
  play: "Play sample call",
  pause: "Pause sample call",
  resume: "Resume sample call",
  replay: "Play again",
  seek: "Playback position",
  position: (at: number, total: number) => `${at} of ${total} seconds`,
  lineHint: "Plays from this line",
  unavailable:
    "The recording didn't load — the transcript below is the whole call.",
  transcript: "Transcript",
  speakers: { agent: "Agent", buyer: "Buyer" } satisfies Record<
    Speaker,
    string
  >,
  resultTitle: "What the call captured",
  result: [
    { label: "Budget", value: "₹90 L" },
    { label: "Location", value: "Whitefield, Bengaluru · 2 BHK" },
    { label: "Buying timeline", value: "Within 12 months · needs a home loan" },
    {
      label: "Next action",
      value: "Site visit, Sat 11:00 AM · WhatsApp confirmation sent",
    },
  ],
  lines: [
    {
      at: 0.3,
      who: "agent",
      text: "Namaste Rohan ji, main Asha bol rahi hoon, Meridian Homes se. Aapne abhi Whitefield ke 2 BHK ke baare mein enquiry ki thi?",
    },
    {
      at: 8.9,
      who: "buyer",
      text: "Haan ji. Budget around 90 lakh hai. Possession kab tak milega?",
    },
    {
      at: 13.5,
      who: "agent",
      text: "Tower B mein December 2027 mein possession hai, aur 2 BHK 90 lakh ke andar available hai. Aap kab tak shift karna chahte hain?",
    },
    { at: 22.8, who: "buyer", text: "Next year tak. Home loan bhi lena hai." },
    {
      at: 25.6,
      who: "agent",
      text: "Bilkul, hum loan partner se bhi connect kara denge. Kya aap Saturday ko site visit ke liye aa sakte hain?",
    },
    { at: 32.5, who: "buyer", text: "Saturday, 11 baje theek rahega." },
    {
      at: 35.3,
      who: "agent",
      text: "Done. Saturday 11 baje ka visit book ho gaya. Location aur details main WhatsApp par bhej rahi hoon.",
    },
  ] satisfies CallLine[],
};
